contrib: disable upstart kpatch.conf install
Do not install the upstart configuration file to avoid this rhpkg
build complaint:

  Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/kpatch-0.6.1-1.el7.noarch
  error: Installed (but unpackaged) file(s) found:
     /etc/init/kpatch.conf
      Installed (but unpackaged) file(s) found:
     /etc/init/kpatch.conf

We'll need to think of a better way to do this upstream, but for now,
just skip the unneeded file on RHEL.

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>